# File: .github/workflows/repo-sync.yml
name: sync-scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: sync-scripts
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: 获取本地仓库
        uses: actions/checkout@master
      - name: 同步文件
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            LXK9301/jd_scripts@master
          FILES: |
            serverless.yml
          TOKEN: ${{ secrets.PAT }}